def generate_synopsis(project_idea, blueprint):
    synopsis = f"""
============================================================
PROJECT SYNOPSIS
============================================================

PROJECT TITLE
AI Student Performance Prediction System


PROBLEM STATEMENT
Students may find it difficult to understand their academic
performance and identify areas where they need improvement.
The proposed system uses artificial intelligence and machine
learning to help predict student academic performance.


OBJECTIVE
The main objective of this project is to develop an AI-based
system that can analyze student-related data and predict
academic performance.


TARGET USERS
- Students
- Project users
- Administrators


PROJECT SCOPE
The system will accept student-related data, process the
information, generate meaningful predictions, store required
information, and display the results clearly.

The project includes:
- Core project functionality
- Database integration
- User interface
- Testing and validation


TECHNOLOGY STACK
- Programming Language: Python
- Frontend: React.js
- Backend: Flask
- Database: MongoDB
- AI/ML: Python AI/ML libraries
- Development Tools: VS Code, Git, GitHub


EXPECTED OUTCOME
The expected outcome is a functional AI-based system that
helps students understand and predict their academic
performance using machine learning techniques.


MILESTONE 2 BLUEPRINT
The synopsis is generated using the project information
and the project blueprint created during Milestone 2.

------------------------------------------------------------
{blueprint}
------------------------------------------------------------

============================================================
END OF SYNOPSIS
============================================================
"""

    return synopsis
def generate_methodology(project_idea, blueprint):
    methodology = f"""
============================================================
PROJECT METHODOLOGY
============================================================

PROJECT TITLE
AI Student Performance Prediction System


1. REQUIREMENT ANALYSIS

The project begins by understanding the problem, identifying
the target users, and defining the functional requirements.

The system is designed to help students predict and understand
their academic performance using an AI-based approach.


2. SYSTEM DESIGN

The system architecture consists of:

- React.js for the frontend
- Flask for the backend
- MongoDB for data storage
- Python-based AI/ML components

The frontend communicates with the Flask backend through APIs.


3. BACKEND DEVELOPMENT

The backend will be developed using Python and Flask.

The backend will:

- Receive user requests
- Process project and student data
- Communicate with the database
- Execute AI/ML functionality
- Return results to the frontend


4. FRONTEND DEVELOPMENT

The frontend will be developed using React.js.

It will provide interfaces for:

- Student interaction
- Project information
- Data input
- Displaying generated results
- Tracking project progress


5. DATABASE INTEGRATION

MongoDB will be used to store the required project and student
information.

The database will provide flexible storage for project data,
progress information, and other required records.


6. AI/ML INTEGRATION

Python-based AI/ML libraries will be used where required.

The AI/ML component will process relevant student data and
support academic performance prediction.


7. PROJECT EXECUTION

The project follows a week-wise execution plan generated by
the Milestone 2 Timeline Planning Agent.

The major stages include:

- Requirement analysis
- System design
- Backend development
- Frontend development
- AI/ML integration
- Testing
- Documentation and finalization


8. TESTING

The system will be tested at multiple levels:

- Unit testing
- API testing
- Integration testing
- End-to-end testing

Identified problems will be fixed before finalization.


9. FINALIZATION

After successful testing, the project documentation will be
completed and the final working system will be prepared for
demonstration.


MILESTONE 2 BLUEPRINT USED

The methodology is generated using the project information and
the project blueprint produced during Milestone 2.

------------------------------------------------------------
{blueprint}
------------------------------------------------------------

============================================================
END OF METHODOLOGY
============================================================
"""

    return methodology
def generate_progress_report(
    project_idea,
    completed_tasks,
    pending_tasks,
    current_progress,
    risks,
    problems,
    next_week_plan
):
    report = f"""
============================================================
PROJECT PROGRESS REPORT
============================================================

PROJECT TITLE
AI Student Performance Prediction System


PROJECT IDEA
{project_idea}


1. COMPLETED TASKS
"""

    for task in completed_tasks:
        report += f"- {task}\n"

    report += f"""

2. PENDING TASKS
"""

    for task in pending_tasks:
        report += f"- {task}\n"

    report += f"""

3. CURRENT PROGRESS
{current_progress}


4. RISKS
"""

    for risk in risks:
        report += f"- {risk}\n"

    report += f"""

5. PROBLEMS FACED
"""

    for problem in problems:
        report += f"- {problem}\n"

    report += f"""

6. NEXT WEEK'S PLAN
"""

    for task in next_week_plan:
        report += f"- {task}\n"

    report += """

============================================================
END OF PROGRESS REPORT
============================================================
"""

    return report