def analyze_progress(original_plan, progress_data, risk_data=None):
    """
    Analyze student progress against the original project timeline.

    original_plan:
        The timeline generated by the Timeline Agent.

    progress_data:
        Information about completed, pending, or delayed tasks.

    risk_data:
        Risk information received from the Risk Agent.
    """

    if risk_data is None:
        risk_data = {}

    completed_tasks = []
    pending_tasks = []
    delayed_tasks = []

    # Analyze each task reported by the student
    for task in progress_data:

        status = task.get("status", "").lower()

        if status == "completed":
            completed_tasks.append(task)

        elif status == "delayed":
            delayed_tasks.append(task)

        else:
            pending_tasks.append(task)

    # Timeline adjustment is required
    # when at least one task has been delayed.
    adjustment_required = len(delayed_tasks) > 0

    return {
        "adjustment_required": adjustment_required,

        "completed_tasks": completed_tasks,

        "pending_tasks": pending_tasks,

        "delayed_tasks": delayed_tasks,

        "risk_information": risk_data
    }
def find_affected_tasks(original_plan, delayed_tasks):
    """
    Find upcoming tasks that may be affected by delayed tasks.
    """

    affected_tasks = []

    weekly_plan = original_plan.get("weekly_plan", [])

    # Check every delayed task
    for delayed_task in delayed_tasks:

        delayed_task_name = delayed_task.get(
            "task",
            ""
        ).lower()

        delayed_week = delayed_task.get(
            "week",
            0
        )

        # Check future weeks
        for week_data in weekly_plan:

            week_number = week_data.get(
                "week",
                0
            )

            if week_number <= delayed_week:
                continue

            tasks = week_data.get(
                "tasks",
                []
            )

            # Check whether future tasks depend on
            # the delayed task
            dependencies = week_data.get(
                "dependencies",
                []
            )

            for task in tasks:

                task_text = task.lower()

                dependency_match = any(
                    delayed_task_name in str(dependency).lower()
                    for dependency in dependencies
                )

                if dependency_match:

                    affected_tasks.append({
                        "week": week_number,
                        "task": task,
                        "delayed_dependency":
                            delayed_task.get("task"),
                        "reason":
                            "Task depends on a delayed task"
                    })

    return affected_tasks

def adjust_timeline(original_plan, progress_data, risk_data=None):
    """
    Adjust the original project timeline based on
    student progress and risk information.
    """

    # Step 1: Analyze student progress
    progress_analysis = analyze_progress(
        original_plan,
        progress_data,
        risk_data
    )

    delayed_tasks = progress_analysis["delayed_tasks"]

    # If there are no delayed tasks,
    # the original timeline does not need adjustment.
    if not delayed_tasks:

        return {
            "adjustment_required": False,
            "message": "No delayed tasks. Original timeline can continue.",
            "updated_plan": original_plan
        }

    # Step 2: Find tasks affected by delays
    affected_tasks = find_affected_tasks(
        original_plan,
        delayed_tasks
    )

    # Make a copy of the original plan
    updated_plan = {
        "project_title": original_plan.get(
            "project_title",
            "Academic Project"
        ),
        "total_duration_weeks": original_plan.get(
            "total_duration_weeks",
            0
        ),
        "weekly_plan": []
    }

    # Step 3: Copy the weekly plan
    for week_data in original_plan.get(
        "weekly_plan",
        []
    ):

        updated_week = {
            "week": week_data.get("week"),
            "milestone": week_data.get(
                "milestone",
                ""
            ),
            "tasks": list(
                week_data.get("tasks", [])
            ),
            "deliverables": list(
                week_data.get("deliverables", [])
            ),
            "dependencies": list(
                week_data.get("dependencies", [])
            )
        }

        updated_plan["weekly_plan"].append(
            updated_week
        )

    # Step 4: Move delayed tasks into
    # the next available week
    for delayed_task in delayed_tasks:

        delayed_task_name = delayed_task.get(
            "task",
            ""
        )

        delayed_week = delayed_task.get(
            "week",
            0
        )

        # Find the delayed task in the plan
        for week_data in updated_plan["weekly_plan"]:

            if week_data["week"] != delayed_week:
                continue

            if delayed_task_name in week_data["tasks"]:

                week_data["tasks"].remove(
                    delayed_task_name
                )

        # Add the delayed task to the next week
        next_week = delayed_week + 1

        for week_data in updated_plan["weekly_plan"]:

            if week_data["week"] == next_week:

                week_data["tasks"].insert(
                    0,
                    delayed_task_name
                )

                break

    return {
        "adjustment_required": True,

        "message":
            "Timeline adjusted because delayed tasks were detected.",

        "delayed_tasks": delayed_tasks,

        "affected_tasks": affected_tasks,

        "updated_plan": updated_plan
    }